# version: '3.8'

services:
  # MinIO - Data Lake
  minio:
    image: minio/minio
    container_name: datalake
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: datalake
      MINIO_ROOT_PASSWORD: datalake
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
