# version: '3.8'

services:
  # MinIO - Data Lake
  minio:
    image: minio/minio
    container_name: datalake
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: datalake
      MINIO_ROOT_PASSWORD: datalake
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # Python 3.11 Slim Container
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-slim
    volumes:
      - ./scripts:/app
    command: tail -f /dev/null

volumes:
  minio_data:
